config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :links do
    member do
      put 'like', to: 'links#upvote'
      put 'dislike', to: 'links#downvote'
    end
    resources :comments
  end

  resources :comments
  resources :users, only: [:show]

  root to: 'links#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, length: { maximum: 2000,
    too_long: "%{count} characters is the maximum allowed" }

  belongs_to :user
end

app/models/link.rb
class Link < ApplicationRecord
  validates :title, :url, presence: true
  validates :title, length: { maximum: 500,
    too_long: "%{count} characters is the maximum allowed" }

  acts_as_votable

  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, :username, presence: true, uniqueness: true
  validates :username, length: { maximum: 150 }

  has_many :links

  has_attached_file :avatar, :styles => { :medium => "200x200>", :thumb => "20x20>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :store_user_location!, if: :storable_location?
  before_action :authenticate_user!

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :avatar])
  end

  def storable_location?
    request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
  end

  def store_user_location!
    store_location_for(:user, request.fullpath)
  end

  def after_sign_out_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || super
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @link, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:link_id, :body, :user_id)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @links = Link.all
  end

  def show
  end

  def new
    @link = current_user.links.build
  end

  def edit
  end

  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @link = Link.find(params[:id])
    @link.upvote_by current_user
    redirect_back fallback_location: root_path
  end

  def downvote
    @link = Link.find(params[:id])
    @link.downvote_by current_user
    redirect_back fallback_location: root_path
  end

  private

    def set_link
      @link = Link.find(params[:id])
    end

    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
  def truncated_link_title(link)
    link_to truncate(link.title, length: 70), link
  end

  def truncated_url_title(link)
    link_to truncate(link.url, length: 30), link.url, target: :blank
  end
end

app/views/comments/_comment.html.erb
<%= div_for(comment) do %>
  <p class="comment-body"><%= comment.body %></p>
  <p>
    <small>Commented <strong><%= time_ago_in_words(comment.created_at) %> ago</strong> by <%= link_to comment.user.username, user_path(comment.user) %></small>
  </p>

  <p class="delete-comment">
    <% if comment.user == current_user %>
      <%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are yousure?' } %>
    <% end %>
  </p>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="nav clearfix">
  <div class="logo">
    <%= link_to fa_icon("grav"), links_path, class: 'logo-link' %>
  </div>
  <% if user_signed_in? %>
    <ul class="nav-list align-right">
      <li class="list-item thumb-avatar"><%= link_to image_tag(current_user.avatar.url(:thumb)), user_path(current_user) %></li>
      <li class="list-item"><%= link_to 'Submit link', new_link_path %></li> |
      <li class="list-item"><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
    </ul>
  <% else %>
    <ul class="nav-list align-right">
      <li class="list-item"><%= link_to 'Sign up', new_user_registration_path %></li> |
      <li class="list-item"><%= link_to 'Sign in', new_user_session_path %></li>
    </ul>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewsAggregatorApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="container clearfix">
      <%= yield %>
    </div>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :link_title, class: 'form-input' %>
  </div>

  <div class="field">
    <%= form.label :url, class: 'uppercase' %>
    <%= form.text_field :url, id: :link_url, class: 'form-input' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'submit-btn' %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1 class="title-lg">Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<% @links.each_with_index do |link, index| %>
  <div class="content">
    <span class="index-number"><%= index + 1 %></span>
    <div class="unvoted">
      <%= link_to like_link_path(link), method: :put, class: 'unvoted-counter' do %>
        <%= fa_icon "arrow-up" %>
        <%= link.get_upvotes.size %>
      <% end %>
      <%= link_to dislike_link_path(link), method: :put, class: 'unvoted-counter' do %>
        <%= fa_icon "arrow-down" %>
        <%= link.get_downvotes.size %>
      <% end %>
    </div>

    <div class="content-link">
      <h2 class="link-title"><%= truncated_link_title(link) %></h2>
      <span class="content-url">
        (<%= truncated_url_title(link) %>)
      </span>
      <p class='submit-info'>
        <small>Submitted <strong><%= time_ago_in_words(link.created_at) %> ago</strong> by <%= link_to link.user.username, user_path(link.user) %></small>
      </p>
    </div>
  </div>
<% end %>

app/views/links/new.html.erb
<h1 class="title-lg">New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<div class="content-link">
  <h2 class="link-title"><%= link_to @link.title, @link.url  %></h2>

  <span class="content-url">
    (<%= truncated_url_title(@link) %>)
  </span>

  <p class='submit-info'>
    <small>Submitted <strong><%= time_ago_in_words(@link.created_at) %> ago</strong> by <%= link_to @link.user.username, user_path(@link.user) %></small>
  </p>

  <div class="link-actions">
    <%= link_to 'Back', links_path %>
    <% if @link.user == current_user %>
      |
    	<%= link_to 'Edit', edit_link_path, class: "btn btn-default" %>
      |
    	<%= link_to 'Delete', @link, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
    <% end %>
  </div>

  <div class="unvoted">
    <%= link_to like_link_path(@link), method: :put, class: 'unvoted-counter' do %>
      <%= fa_icon "arrow-up" %>
      <%= @link.get_upvotes.size %>
    <% end %>
    <%= link_to dislike_link_path(@link), method: :put, class: 'unvoted-counter' do %>
      <%= fa_icon "arrow-down" %>
      <%= @link.get_downvotes.size %>
    <% end %>
  </div>
</div>

<div class="comments-block">
  <h3 class="title-sm"><%= @link.comments.length %> Comments</h3>

  <%= render partial: @link.comments %>

  <div class="add-comment">
    <% if user_signed_in? %>
      <h3 class="title-sm">Add comment</h3>

      <%= simple_form_for [@link, Comment.new] do |f| %>
        <%= f.text_area :body, rows: 14, cols: 80 %>
        <br>
        <%= f.submit 'Add comment', class: 'submit-btn' %>
      <% end %>

    <% else %>
      <h3 class="title-sm">
        If you want to leave a comment, please <%= link_to 'Sign in', new_user_session_path %>
      </h3>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-info align-left">
  <%= image_tag @user.avatar.url(:medium), class: 'avatar' %>

  <h1 class="title-lg">@<%= @user.username %></h1>

  <%= link_to 'Back', links_path %>
  <% if @user == current_user %>
    |
    <%= link_to 'Edit profile', edit_user_registration_path %>
  <% end %>
</div>

<br>

<div class="user-links">
  <% if @user.links.empty? %>
    <h2 class="title-sm">You have not added any links yet</h2>
    <h4>Want submit <%= link_to 'link', new_link_path %>?</h4>
  <% else %>
    <h2 class="title-sm">All links:</h2>

    <ol class="all-links">
      <% @user.links.each do |link| %>
        <li class="content-link">
          <h2 class="link-title"><%= truncated_link_title(link)  %></h2>
          <span class="content-url">
            (<%= truncated_url_title(link) %>)
          </span>
          <p class='submit-info'>
            <small>Submitted <strong><%= time_ago_in_words(link.created_at) %> ago</strong></small>
          </p>
        </li>
        <br>

      <% end %>
    </ol>
  <% end %>
</div>